const n1 = 10;
const n2 = 15;
const n3 = 20;
const n4 = 5;
const isSum50 = (n1 + n2 + n3 + n4) === 50;
const isTwoOdd = (n1 % 2) + (n2 % 2) + (n3 % 2) + (n4 % 2) >= 2;
const isOver25 = n1 > 25 || n2 > 25 || n3 > 25 || n4 > 25;
const isUnique = n1 !== n2 && n1 !== n3 && n1 !== n4 && n2 !== n3 && n2 !== n4 && n3 !== n4;
const isValid = isSum50 && isTwoOdd && !isOver25 && isUnique;
console.log(`Are the numbers valid? ${isValid}`);
const distance = 1500; 
const budget = 175; 
const fuelCost = 3;
const speeds = [55, 60, 75];
const efficiencies = [30, 28, 23];
speeds.forEach((speed, index) => {
    const gallonsNeeded = distance / efficiencies[index];
    const totalCost = gallonsNeeded * fuelCost;
    const hoursNeeded = distance / speed;
    console.log(`At ${speed} mph:`);
    console.log(`Gallons needed: ${gallonsNeeded}`);
    console.log(`Total cost: $${totalCost}`);
    console.log(`Trip duration: ${hoursNeeded} hours`);
    console.log(`Is the budget enough? ${totalCost <= budget}`);
});